#set($command = $helper.getByName($command-name, $robot))
#header()

\#include "#class($command.name).h"

#class($command.name)::#class($command.name)() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
#@autogenerated_code("requires", "	")
#parse("${exporter-path}Command-requires.cpp")
#end
}

void #class($command.name)::Initialize() {
	
}

void #class($command.name)::Execute() {
	
}

bool #class($command.name)::IsFinished() {
	return false;
}

void #class($command.name)::End() {
	
}

void #class($command.name)::Interrupted() {

}
